In [1]:
import numpy as np

In [2]:
#Esercizio1
array = np.arange(10,50)
print(array)
print(array.dtype)
array = array.astype(float)
print(array.dtype)
print(array.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int64
float64
(40,)


# Esercizio2

In [4]:
rand_array = np.random.randint(10,51,20)
print(rand_array)

[20 12 20 24 42 46 12 35 22 49 44 46 37 14 34 23 47 44 41 17]


In [6]:
primi_10 = rand_array[:10]
print(primi_10)

[20 12 20 24 42 46 12 35 22 49]


In [8]:
ultimi_5 = rand_array[len(rand_array)-5:len(rand_array)]
print(ultimi_5)

[23 47 44 41 17]


In [10]:
elementi_5_15 = rand_array[5:15]
print(elementi_5_15)

[46 12 35 22 49 44 46 37 14 34]


In [15]:
print(rand_array[2::3])

[20 46 22 46 34 44]


[]
