In [1]:
import numpy as np

In [2]:
#Esercizio1
array = np.arange(10,50)
print(array)
print(array.dtype)
array = array.astype(float)
print(array.dtype)
print(array.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int64
float64
(40,)


# Esercizio2

In [4]:
rand_array = np.random.randint(10,51,20)
print(rand_array)

[20 12 20 24 42 46 12 35 22 49 44 46 37 14 34 23 47 44 41 17]


In [6]:
primi_10 = rand_array[:10]
print(primi_10)

[20 12 20 24 42 46 12 35 22 49]


In [25]:
ultimi_5 = rand_array[len(rand_array)-5:len(rand_array)]
print(ultimi_5)

ultimi_5 = rand_array[-5::]
print(ultimi_5)

[23 47 44 41 17]
[23 47 44 41 17]


In [10]:
elementi_5_15 = rand_array[5:15]
print(elementi_5_15)

[46 12 35 22 49 44 46 37 14 34]


In [29]:
print(rand_array[2::3])

indices = [i for i in range(2, len(rand_array), 3)]
print(rand_array[indices])

[20 46 22 46 34 44]
[20 46 22 46 34 44]


# Esercizio 3

In [30]:
array = np.linspace(0,1,12)
array

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [32]:
matrix1 = array.reshape(3,4)
matrix1

array([[0.        , 0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455, 0.63636364],
       [0.72727273, 0.81818182, 0.90909091, 1.        ]])

In [39]:
matrix2 = np.random.random((3,4))

matrix2

array([[0.66603431, 0.61085728, 0.40370209, 0.71228058],
       [0.56885563, 0.91596041, 0.56434618, 0.33161959],
       [0.15898712, 0.84199496, 0.50182304, 0.16722365]])

In [41]:
print('Somma matrice1:', matrix1.sum())
print('Somma matrice 2:', matrix2.sum())

Somma matrice1: 6.0 6.0
Somma matrice 2: 6.443684827234405


# Esercizio 4

In [42]:
array = np.linspace(0,10,50)
array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [43]:
rand_array = np.random.random(50)
rand_array

array([0.9851894 , 0.50985025, 0.85444452, 0.4367782 , 0.56822378,
       0.19321173, 0.92080778, 0.36862247, 0.00335421, 0.08551434,
       0.63451299, 0.71616666, 0.85190457, 0.53654385, 0.22462798,
       0.92349437, 0.08101452, 0.49824643, 0.02683997, 0.4937795 ,
       0.25969626, 0.65552419, 0.70798655, 0.72514753, 0.17351639,
       0.1139695 , 0.80204103, 0.77291023, 0.17076885, 0.65799477,
       0.83645493, 0.88711745, 0.66488841, 0.49479489, 0.38358045,
       0.33863205, 0.98225566, 0.88382287, 0.82193639, 0.4131389 ,
       0.83321687, 0.40053928, 0.71517066, 0.77715375, 0.92092732,
       0.95606512, 0.02321275, 0.47722284, 0.29201555, 0.61441756])

In [44]:
sum_array = np.add(array, rand_array)
sum_array

array([ 0.9851894 ,  0.71393188,  1.26260778,  1.0490231 ,  1.38455031,
        1.21361989,  2.14529757,  1.7971939 ,  1.63600727,  1.92224903,
        2.67532932,  2.96106462,  3.30088417,  3.18960507,  3.08177084,
        3.98471886,  3.34632065,  3.96763419,  3.70030936,  4.37133052,
        4.34132892,  4.94123848,  5.19778246,  5.41902508,  5.07147558,
        5.21601031,  6.10816348,  6.28311431,  5.88505456,  6.57636212,
        6.95890391,  7.21364807,  7.19550066,  7.22948877,  7.32235596,
        7.48148919,  8.32919443,  8.43484328,  8.57703843,  8.37232257,
        8.99648217,  8.76788621,  9.28659923,  9.55266395,  9.90051916,
       10.13973859,  9.41096785, 10.06905958, 10.08793392, 10.61441756])

In [45]:
total_sum = sum_array.sum()
total_sum

np.float64(277.66924648986355)

In [50]:
sum_g5 = np.array([num for num in sum_array if num > 5]).sum()
print(sum_g5)
sum2 = np.sum(sum_array, where = sum_array > 5 )
print(sum2)


np.float64(219.69804138729367)