In [1]:
import numpy as np

In [2]:
#Esercizio1
array = np.arange(10,50)
print(array)
print(array.dtype)
array = array.astype(float)
print(array.dtype)
print(array.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int64
float64
(40,)


# Esercizio2

In [4]:
rand_array = np.random.randint(10,51,20)
print(rand_array)

[20 12 20 24 42 46 12 35 22 49 44 46 37 14 34 23 47 44 41 17]


In [6]:
primi_10 = rand_array[:10]
print(primi_10)

[20 12 20 24 42 46 12 35 22 49]


In [25]:
ultimi_5 = rand_array[len(rand_array)-5:len(rand_array)]
print(ultimi_5)

ultimi_5 = rand_array[-5::]
print(ultimi_5)

[23 47 44 41 17]
[23 47 44 41 17]


In [10]:
elementi_5_15 = rand_array[5:15]
print(elementi_5_15)

[46 12 35 22 49 44 46 37 14 34]


In [29]:
print(rand_array[2::3])

indices = [i for i in range(2, len(rand_array), 3)]
print(rand_array[indices])

[20 46 22 46 34 44]
[20 46 22 46 34 44]


# Esercizio 3

In [30]:
array = np.linspace(0,1,12)
array

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [32]:
matrix1 = array.reshape(3,4)
matrix1

array([[0.        , 0.09090909, 0.18181818, 0.27272727],
       [0.36363636, 0.45454545, 0.54545455, 0.63636364],
       [0.72727273, 0.81818182, 0.90909091, 1.        ]])

In [39]:
matrix2 = np.random.random((3,4))

matrix2

array([[0.66603431, 0.61085728, 0.40370209, 0.71228058],
       [0.56885563, 0.91596041, 0.56434618, 0.33161959],
       [0.15898712, 0.84199496, 0.50182304, 0.16722365]])

In [40]:
print('Somma matrice1:', matrix1.sum())
print('Somma matrice 2:', matrix2.sum())

Somma matrice1: 6.0
Somma matrice 2: 6.443684827234405
